### ISSUE TITLE
Uncaught TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by spalger** [oriSomething/string-case#3]
After some recent update to Atom using the string-case conversion shortcuts no longer works when the cursor is just at the word to convert (rather than selecting it). I assume this is supposed to work, and I used it all the time when it did work.

Steps to reproduce:

1. use string-case shortcut without a selection
2. error is thrown and then selection is expanded to nearest word
3. use the shortcut again, after the selection is expanded and it correctly converts

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [string-case](https://github.com/oriSomething/string-case) package 0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'start' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/range.js:33

TypeError: Cannot read property 'start' of undefined
    at Function.module.exports.Range.fromObject (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/range.js:33:37)
    at TextBuffer.module.exports.TextBuffer.getTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:539:53)
    at TextEditor.getTextInBufferRange (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1165:30)
    at /packages/string-case/lib/string-case.js:43:29
    at Array.forEach (native)
    at Object.transformSelections (/packages/string-case/lib/string-case.js:38:8)
    at Object.snake (/packages/string-case/lib/string-case.js:68:10)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:51.2.0 core:paste (input.hidden-input)
  5x -0:50.9.0 find-and-replace:find-next (input.hidden-input)
     -0:48.1.0 core:save (input.hidden-input)
  2x -0:45.5.0 core:copy (input.hidden-input)
     -0:29.7.0 core:save (input.hidden-input)
  2x -0:16.8.0 core:backspace (input.hidden-input)
     -0:10.3.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:10.3.0 autocomplete-plus:confirm (input.hidden-input)
     -0:10 core:move-right (input.hidden-input)
     -0:07.3.0 core:move-down (input.hidden-input)
     -0:06.9.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:06.9.0 autocomplete-plus:confirm (input.hidden-input)
  2x -0:06.4.0 string-case:snakecase (input.hidden-input)
     -0:04.8.0 core:move-right (input.hidden-input)
  9x -0:04.5.0 core:backspace (input.hidden-input)
     -0:03.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
asciidoc-assistant 0.2.2 
asciidoc-image-helper 1.0.0 
asciidoc-preview 2.10.3 
atom-prettify 0.1.3 
atom-typescript 11.0.10 
autocomplete-asciidoc 0.1.2 
busy-signal 1.4.3 
copy-with-style 1.1.0 
docblockr 0.13.4 
editorconfig 2.2.2 
file-icons 2.1.15 
gz-opener 0.2.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-asciidoc 1.11.0 
language-babel 2.81.1 
language-diff 0.7.0 
language-docker 1.1.8 
language-elm 1.5.0 
language-gradle 0.0.5 
language-graphql 0.9.0 
language-groovy 0.7.0 
language-ini 1.19.0 
language-logstash 0.1.7 
language-nginx 0.8.0 
language-pegjs 0.5.0 
language-pug 0.0.21 
language-rust 0.4.12 
language-vue 0.23.1 
lines 0.13.1 
linter 2.2.0 
linter-docker 0.2.1 
linter-eslint 8.4.0 
linter-flow 5.6.1 
linter-shellcheck 1.4.6 
linter-tslint 1.9.0 
linter-ui-default 1.6.10 
markdown-preview-plus 2.4.16 
markdown-writer 2.7.3 
pretty-json 1.6.4 
string-case 0.1.0 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by spalger** [comment]
Oh, just noticed the deprecation
